openapi : 3.0.0
info:
  title: Social App
  description: Our first social app
  version: 1.0.1
servers:
  - url: http://localhost:4000/
    description: Our main server
  - url: http://localhost:4000/
    description: Main server , just ignore it
components:
  securitySchemes:
    BasicAuth:
      type: http
      scheme: basic
    BearerAuth:
      type: http
      scheme: bearer
paths:
  /instagram:
    get:
      summary: returns username , followers and follows
      responses:
        '200': #status code
         description: returns an object
         content:
          application/json:
            schema:
              type: object
              properties:
                username:
                  type: string
                followers:
                  type: string
                follows:
                  type: string
  /{token}:
    get:
      summary: returns whatever is in parameters
      parameters:
        - name: token
          default: 5
          in: path
          schema:
              type: object
              properties:
                params:
                  type: string
      responses:
        '200': #status code
          description: returns an object
          content:
          application/json:
            schema:
              type: object
              properties:
                username:
                  type: string
                followers:
                  type: string
                follows:
                  type: string